In [20]:
import pandas as pd
import numpy as np

df = pd.read_csv("../Data/heart_disease_uci.csv")

print(df.shape)
df.head()

(920, 16)

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
0,1,63,Male,Cleveland,typical angina,145.0,233.0,True,lv hypertrophy,150.0,False,2.3,downsloping,0.0,fixed defect,0
1,2,67,Male,Cleveland,asymptomatic,160.0,286.0,False,lv hypertrophy,108.0,True,1.5,flat,3.0,normal,2
2,3,67,Male,Cleveland,asymptomatic,120.0,229.0,False,lv hypertrophy,129.0,True,2.6,flat,2.0,reversable defect,1
3,4,37,Male,Cleveland,non-anginal,130.0,250.0,False,normal,187.0,False,3.5,downsloping,0.0,normal,0
4,5,41,Female,Cleveland,atypical angina,130.0,204.0,False,lv hypertrophy,172.0,False,1.4,upsloping,0.0,normal,0

In [21]:
print(df.columns)
df.sample(10)

Index(['id', 'age', 'sex', 'dataset', 'cp', 'trestbps', 'chol', 'fbs',
       'restecg', 'thalch', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num'],
      dtype='object')

,id,age,sex,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal,num
552,553,58,Male,Hungary,non-anginal,160.0,211.0,True,st-t abnormality,92.0,False,0.0,NaN,NaN,NaN,1
551,552,57,Male,Hungary,asymptomatic,150.0,255.0,False,normal,92.0,True,3.0,flat,NaN,NaN,1
768,769,59,Male,VA Long Beach,non-anginal,NaN,0.0,False,normal,128.0,True,2.0,downsloping,NaN,NaN,2
251,252,58,Male,Cleveland,asymptomatic,146.0,218.0,False,normal,105.0,False,2.0,flat,1.0,reversable defect,1
200,201,50,Female,Cleveland,asymptomatic,110.0,254.0,False,lv hypertrophy,159.0,False,0.0,upsloping,0.0,normal,0
85,86,44,Male,Cleveland,non-anginal,140.0,235.0,False,lv hypertrophy,180.0,False,0.0,upsloping,0.0,normal,0
460,461,55,Female,Hungary,atypical angina,122.0,320.0,False,normal,155.0,False,0.0,NaN,NaN,NaN,0
140,141,59,Male,Cleveland,atypical angina,140.0,221.0,False,normal,164.0,True,0.0,upsloping,0.0,normal,0
777,778,60,Male,VA Long Beach,non-anginal,NaN,316.0,True,st-t abnormality,NaN,NaN,NaN,NaN,NaN,NaN,3
367,368,43,Female,Hungary,atypical angina,150.0,186.0,False,normal,154.0,False,0.0,NaN,NaN,NaN,0

In [22]:
df.rename(columns={"num": "target"}, inplace=True)

In [23]:
df.describe()

,id,age,trestbps,chol,thalch,oldpeak,ca,target
count,920.000000,920.000000,861.000000,890.000000,865.000000,858.000000,309.000000,920.000000
mean,460.500000,53.510870,132.132404,199.130337,137.545665,0.878788,0.676375,0.995652
std,265.725422,9.424685,19.066070,110.780810,25.926276,1.091226,0.935653,1.142693
min,1.000000,28.000000,0.000000,0.000000,60.000000,-2.600000,0.000000,0.000000
25%,230.750000,47.000000,120.000000,175.000000,120.000000,0.000000,0.000000,0.000000
50%,460.500000,54.000000,130.000000,223.000000,140.000000,0.500000,0.000000,1.000000
75%,690.250000,60.000000,140.000000,268.000000,157.000000,1.500000,1.000000,2.000000
max,920.000000,77.000000,200.000000,603.000000,202.000000,6.200000,3.000000,4.000000

In [24]:
df.isnull().sum()

id            0
age           0
sex           0
dataset       0
cp            0
trestbps     59
chol         30
fbs          90
restecg       2
thalch       55
exang        55
oldpeak      62
slope       309
ca          611
thal        486
target        0
dtype: int64

In [25]:
df.drop(["id", "dataset"], axis=1, inplace=True, errors="ignore")

In [26]:
df["target"] = (df["target"] > 0).astype(int)
df["target"].value_counts()

target
1    509
0    411
Name: count, dtype: int64

In [27]:
X = df.drop("target", axis=1)
y = df["target"]

print(X.shape, y.shape)

(920, 13) (920,)

In [29]:
df["thal"].value_counts()

thal
normal               196
reversable defect    192
fixed defect          46
Name: count, dtype: int64